### ISSUE TITLE
¿Diferencias entre formal e informal?

### ISSUE THREAD

**Issue by iec989** [Zeokat/flarum-ext-spanish#1]
Gracias por el trabajo ante todo.

¿No acabo de ver las diferencias entre la opción _formal_ e _informal_? Cuando cambio la opción, no acabo de ver ninguna diferencia.

Por otro lado, veo que todo está escrito de _usted_, lo cual puede resultar "raro" en foros de discusiones informales, al menos en España. 

Me gustaría poder participar e incluir una opción usando el _tú_ en vez del _usted_.

**Comment by Zeokat** [comment]
Hola @iec989 , esta traducción se ha quedado obsoleta, te recomiendo que uses la que está disponible para la versión Beta 7 en el enlace: https://github.com/FlarumES/Spanish

Por mi parte actualizaré esta traducción cuando lancen la Beta 8. Lo haré unicamente con el lenguaje informal, que usará "Tu" en lugar de "Usted".
